/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.SC2APIProtocol.Action');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.SC2APIProtocol.ActionChat');
goog.require('proto.SC2APIProtocol.ActionRaw');
goog.require('proto.SC2APIProtocol.ActionSpatial');
goog.require('proto.SC2APIProtocol.ActionUI');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SC2APIProtocol.Action = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SC2APIProtocol.Action.repeatedFields_, null);
};
goog.inherits(proto.SC2APIProtocol.Action, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SC2APIProtocol.Action.displayName = 'proto.SC2APIProtocol.Action';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SC2APIProtocol.Action.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SC2APIProtocol.Action.prototype.toObject = function(opt_includeInstance) {
  return proto.SC2APIProtocol.Action.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SC2APIProtocol.Action} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SC2APIProtocol.Action.toObject = function(includeInstance, msg) {
  var f, obj = {
    actionRaw: (f = msg.getActionRaw()) && proto.SC2APIProtocol.ActionRaw.toObject(includeInstance, f),
    actionFeatureLayer: (f = msg.getActionFeatureLayer()) && proto.SC2APIProtocol.ActionSpatial.toObject(includeInstance, f),
    actionRender: (f = msg.getActionRender()) && proto.SC2APIProtocol.ActionSpatial.toObject(includeInstance, f),
    actionUi: (f = msg.getActionUi()) && proto.SC2APIProtocol.ActionUI.toObject(includeInstance, f),
    chatList: jspb.Message.toObjectList(msg.getChatList(),
    proto.SC2APIProtocol.ActionChat.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SC2APIProtocol.Action}
 */
proto.SC2APIProtocol.Action.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SC2APIProtocol.Action;
  return proto.SC2APIProtocol.Action.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SC2APIProtocol.Action} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SC2APIProtocol.Action}
 */
proto.SC2APIProtocol.Action.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.SC2APIProtocol.ActionRaw;
      reader.readMessage(value,proto.SC2APIProtocol.ActionRaw.deserializeBinaryFromReader);
      msg.setActionRaw(value);
      break;
    case 2:
      var value = new proto.SC2APIProtocol.ActionSpatial;
      reader.readMessage(value,proto.SC2APIProtocol.ActionSpatial.deserializeBinaryFromReader);
      msg.setActionFeatureLayer(value);
      break;
    case 3:
      var value = new proto.SC2APIProtocol.ActionSpatial;
      reader.readMessage(value,proto.SC2APIProtocol.ActionSpatial.deserializeBinaryFromReader);
      msg.setActionRender(value);
      break;
    case 4:
      var value = new proto.SC2APIProtocol.ActionUI;
      reader.readMessage(value,proto.SC2APIProtocol.ActionUI.deserializeBinaryFromReader);
      msg.setActionUi(value);
      break;
    case 5:
      var value = new proto.SC2APIProtocol.ActionChat;
      reader.readMessage(value,proto.SC2APIProtocol.ActionChat.deserializeBinaryFromReader);
      msg.addChat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SC2APIProtocol.Action.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SC2APIProtocol.Action.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SC2APIProtocol.Action} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SC2APIProtocol.Action.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActionRaw();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.SC2APIProtocol.ActionRaw.serializeBinaryToWriter
    );
  }
  f = message.getActionFeatureLayer();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.SC2APIProtocol.ActionSpatial.serializeBinaryToWriter
    );
  }
  f = message.getActionRender();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.SC2APIProtocol.ActionSpatial.serializeBinaryToWriter
    );
  }
  f = message.getActionUi();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.SC2APIProtocol.ActionUI.serializeBinaryToWriter
    );
  }
  f = message.getChatList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.SC2APIProtocol.ActionChat.serializeBinaryToWriter
    );
  }
};


/**
 * optional ActionRaw action_raw = 1;
 * @return {?proto.SC2APIProtocol.ActionRaw}
 */
proto.SC2APIProtocol.Action.prototype.getActionRaw = function() {
  return /** @type{?proto.SC2APIProtocol.ActionRaw} */ (
    jspb.Message.getWrapperField(this, proto.SC2APIProtocol.ActionRaw, 1));
};


/** @param {?proto.SC2APIProtocol.ActionRaw|undefined} value */
proto.SC2APIProtocol.Action.prototype.setActionRaw = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.SC2APIProtocol.Action.prototype.clearActionRaw = function() {
  this.setActionRaw(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.Action.prototype.hasActionRaw = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ActionSpatial action_feature_layer = 2;
 * @return {?proto.SC2APIProtocol.ActionSpatial}
 */
proto.SC2APIProtocol.Action.prototype.getActionFeatureLayer = function() {
  return /** @type{?proto.SC2APIProtocol.ActionSpatial} */ (
    jspb.Message.getWrapperField(this, proto.SC2APIProtocol.ActionSpatial, 2));
};


/** @param {?proto.SC2APIProtocol.ActionSpatial|undefined} value */
proto.SC2APIProtocol.Action.prototype.setActionFeatureLayer = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.SC2APIProtocol.Action.prototype.clearActionFeatureLayer = function() {
  this.setActionFeatureLayer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.Action.prototype.hasActionFeatureLayer = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ActionSpatial action_render = 3;
 * @return {?proto.SC2APIProtocol.ActionSpatial}
 */
proto.SC2APIProtocol.Action.prototype.getActionRender = function() {
  return /** @type{?proto.SC2APIProtocol.ActionSpatial} */ (
    jspb.Message.getWrapperField(this, proto.SC2APIProtocol.ActionSpatial, 3));
};


/** @param {?proto.SC2APIProtocol.ActionSpatial|undefined} value */
proto.SC2APIProtocol.Action.prototype.setActionRender = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.SC2APIProtocol.Action.prototype.clearActionRender = function() {
  this.setActionRender(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.Action.prototype.hasActionRender = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ActionUI action_ui = 4;
 * @return {?proto.SC2APIProtocol.ActionUI}
 */
proto.SC2APIProtocol.Action.prototype.getActionUi = function() {
  return /** @type{?proto.SC2APIProtocol.ActionUI} */ (
    jspb.Message.getWrapperField(this, proto.SC2APIProtocol.ActionUI, 4));
};


/** @param {?proto.SC2APIProtocol.ActionUI|undefined} value */
proto.SC2APIProtocol.Action.prototype.setActionUi = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.SC2APIProtocol.Action.prototype.clearActionUi = function() {
  this.setActionUi(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.Action.prototype.hasActionUi = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated ActionChat chat = 5;
 * @return {!Array.<!proto.SC2APIProtocol.ActionChat>}
 */
proto.SC2APIProtocol.Action.prototype.getChatList = function() {
  return /** @type{!Array.<!proto.SC2APIProtocol.ActionChat>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SC2APIProtocol.ActionChat, 5));
};


/** @param {!Array.<!proto.SC2APIProtocol.ActionChat>} value */
proto.SC2APIProtocol.Action.prototype.setChatList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.SC2APIProtocol.ActionChat=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SC2APIProtocol.ActionChat}
 */
proto.SC2APIProtocol.Action.prototype.addChat = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.SC2APIProtocol.ActionChat, opt_index);
};


proto.SC2APIProtocol.Action.prototype.clearChatList = function() {
  this.setChatList([]);
};


