/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.SC2APIProtocol.InterfaceOptions');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.SC2APIProtocol.SpatialCameraSetup');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SC2APIProtocol.InterfaceOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SC2APIProtocol.InterfaceOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SC2APIProtocol.InterfaceOptions.displayName = 'proto.SC2APIProtocol.InterfaceOptions';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SC2APIProtocol.InterfaceOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.SC2APIProtocol.InterfaceOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SC2APIProtocol.InterfaceOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SC2APIProtocol.InterfaceOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    raw: jspb.Message.getField(msg, 1),
    score: jspb.Message.getField(msg, 2),
    featureLayer: (f = msg.getFeatureLayer()) && proto.SC2APIProtocol.SpatialCameraSetup.toObject(includeInstance, f),
    render: (f = msg.getRender()) && proto.SC2APIProtocol.SpatialCameraSetup.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SC2APIProtocol.InterfaceOptions}
 */
proto.SC2APIProtocol.InterfaceOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SC2APIProtocol.InterfaceOptions;
  return proto.SC2APIProtocol.InterfaceOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SC2APIProtocol.InterfaceOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SC2APIProtocol.InterfaceOptions}
 */
proto.SC2APIProtocol.InterfaceOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRaw(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setScore(value);
      break;
    case 3:
      var value = new proto.SC2APIProtocol.SpatialCameraSetup;
      reader.readMessage(value,proto.SC2APIProtocol.SpatialCameraSetup.deserializeBinaryFromReader);
      msg.setFeatureLayer(value);
      break;
    case 4:
      var value = new proto.SC2APIProtocol.SpatialCameraSetup;
      reader.readMessage(value,proto.SC2APIProtocol.SpatialCameraSetup.deserializeBinaryFromReader);
      msg.setRender(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SC2APIProtocol.InterfaceOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SC2APIProtocol.InterfaceOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SC2APIProtocol.InterfaceOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SC2APIProtocol.InterfaceOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {boolean} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBool(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getFeatureLayer();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.SC2APIProtocol.SpatialCameraSetup.serializeBinaryToWriter
    );
  }
  f = message.getRender();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.SC2APIProtocol.SpatialCameraSetup.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool raw = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.SC2APIProtocol.InterfaceOptions.prototype.getRaw = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.SC2APIProtocol.InterfaceOptions.prototype.setRaw = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.SC2APIProtocol.InterfaceOptions.prototype.clearRaw = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.InterfaceOptions.prototype.hasRaw = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool score = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.SC2APIProtocol.InterfaceOptions.prototype.getScore = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.SC2APIProtocol.InterfaceOptions.prototype.setScore = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.SC2APIProtocol.InterfaceOptions.prototype.clearScore = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.InterfaceOptions.prototype.hasScore = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SpatialCameraSetup feature_layer = 3;
 * @return {?proto.SC2APIProtocol.SpatialCameraSetup}
 */
proto.SC2APIProtocol.InterfaceOptions.prototype.getFeatureLayer = function() {
  return /** @type{?proto.SC2APIProtocol.SpatialCameraSetup} */ (
    jspb.Message.getWrapperField(this, proto.SC2APIProtocol.SpatialCameraSetup, 3));
};


/** @param {?proto.SC2APIProtocol.SpatialCameraSetup|undefined} value */
proto.SC2APIProtocol.InterfaceOptions.prototype.setFeatureLayer = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.SC2APIProtocol.InterfaceOptions.prototype.clearFeatureLayer = function() {
  this.setFeatureLayer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.InterfaceOptions.prototype.hasFeatureLayer = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional SpatialCameraSetup render = 4;
 * @return {?proto.SC2APIProtocol.SpatialCameraSetup}
 */
proto.SC2APIProtocol.InterfaceOptions.prototype.getRender = function() {
  return /** @type{?proto.SC2APIProtocol.SpatialCameraSetup} */ (
    jspb.Message.getWrapperField(this, proto.SC2APIProtocol.SpatialCameraSetup, 4));
};


/** @param {?proto.SC2APIProtocol.SpatialCameraSetup|undefined} value */
proto.SC2APIProtocol.InterfaceOptions.prototype.setRender = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.SC2APIProtocol.InterfaceOptions.prototype.clearRender = function() {
  this.setRender(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.InterfaceOptions.prototype.hasRender = function() {
  return jspb.Message.getField(this, 4) != null;
};


