/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.SC2APIProtocol.PlayerInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.SC2APIProtocol.Difficulty');
goog.forwardDeclare('proto.SC2APIProtocol.PlayerType');
goog.forwardDeclare('proto.SC2APIProtocol.Race');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SC2APIProtocol.PlayerInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SC2APIProtocol.PlayerInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SC2APIProtocol.PlayerInfo.displayName = 'proto.SC2APIProtocol.PlayerInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SC2APIProtocol.PlayerInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.SC2APIProtocol.PlayerInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SC2APIProtocol.PlayerInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SC2APIProtocol.PlayerInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    playerId: jspb.Message.getField(msg, 1),
    type: jspb.Message.getField(msg, 2),
    raceRequested: jspb.Message.getField(msg, 3),
    raceActual: jspb.Message.getField(msg, 4),
    difficulty: jspb.Message.getField(msg, 5)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SC2APIProtocol.PlayerInfo}
 */
proto.SC2APIProtocol.PlayerInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SC2APIProtocol.PlayerInfo;
  return proto.SC2APIProtocol.PlayerInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SC2APIProtocol.PlayerInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SC2APIProtocol.PlayerInfo}
 */
proto.SC2APIProtocol.PlayerInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPlayerId(value);
      break;
    case 2:
      var value = /** @type {!proto.SC2APIProtocol.PlayerType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {!proto.SC2APIProtocol.Race} */ (reader.readEnum());
      msg.setRaceRequested(value);
      break;
    case 4:
      var value = /** @type {!proto.SC2APIProtocol.Race} */ (reader.readEnum());
      msg.setRaceActual(value);
      break;
    case 5:
      var value = /** @type {!proto.SC2APIProtocol.Difficulty} */ (reader.readEnum());
      msg.setDifficulty(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SC2APIProtocol.PlayerInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SC2APIProtocol.PlayerInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SC2APIProtocol.PlayerInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SC2APIProtocol.PlayerInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = /** @type {!proto.SC2APIProtocol.PlayerType} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {!proto.SC2APIProtocol.Race} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = /** @type {!proto.SC2APIProtocol.Race} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = /** @type {!proto.SC2APIProtocol.Difficulty} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * optional uint32 player_id = 1;
 * @return {number}
 */
proto.SC2APIProtocol.PlayerInfo.prototype.getPlayerId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.SC2APIProtocol.PlayerInfo.prototype.setPlayerId = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.SC2APIProtocol.PlayerInfo.prototype.clearPlayerId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.PlayerInfo.prototype.hasPlayerId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional PlayerType type = 2;
 * @return {!proto.SC2APIProtocol.PlayerType}
 */
proto.SC2APIProtocol.PlayerInfo.prototype.getType = function() {
  return /** @type {!proto.SC2APIProtocol.PlayerType} */ (jspb.Message.getFieldWithDefault(this, 2, 1));
};


/** @param {!proto.SC2APIProtocol.PlayerType} value */
proto.SC2APIProtocol.PlayerInfo.prototype.setType = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.SC2APIProtocol.PlayerInfo.prototype.clearType = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.PlayerInfo.prototype.hasType = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Race race_requested = 3;
 * @return {!proto.SC2APIProtocol.Race}
 */
proto.SC2APIProtocol.PlayerInfo.prototype.getRaceRequested = function() {
  return /** @type {!proto.SC2APIProtocol.Race} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.SC2APIProtocol.Race} value */
proto.SC2APIProtocol.PlayerInfo.prototype.setRaceRequested = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.SC2APIProtocol.PlayerInfo.prototype.clearRaceRequested = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.PlayerInfo.prototype.hasRaceRequested = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Race race_actual = 4;
 * @return {!proto.SC2APIProtocol.Race}
 */
proto.SC2APIProtocol.PlayerInfo.prototype.getRaceActual = function() {
  return /** @type {!proto.SC2APIProtocol.Race} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.SC2APIProtocol.Race} value */
proto.SC2APIProtocol.PlayerInfo.prototype.setRaceActual = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.SC2APIProtocol.PlayerInfo.prototype.clearRaceActual = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.PlayerInfo.prototype.hasRaceActual = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Difficulty difficulty = 5;
 * @return {!proto.SC2APIProtocol.Difficulty}
 */
proto.SC2APIProtocol.PlayerInfo.prototype.getDifficulty = function() {
  return /** @type {!proto.SC2APIProtocol.Difficulty} */ (jspb.Message.getFieldWithDefault(this, 5, 1));
};


/** @param {!proto.SC2APIProtocol.Difficulty} value */
proto.SC2APIProtocol.PlayerInfo.prototype.setDifficulty = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.SC2APIProtocol.PlayerInfo.prototype.clearDifficulty = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.PlayerInfo.prototype.hasDifficulty = function() {
  return jspb.Message.getField(this, 5) != null;
};


