/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.SC2APIProtocol.PlayerInfoExtra');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.SC2APIProtocol.PlayerInfo');
goog.require('proto.SC2APIProtocol.PlayerResult');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SC2APIProtocol.PlayerInfoExtra = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SC2APIProtocol.PlayerInfoExtra, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SC2APIProtocol.PlayerInfoExtra.displayName = 'proto.SC2APIProtocol.PlayerInfoExtra';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.toObject = function(opt_includeInstance) {
  return proto.SC2APIProtocol.PlayerInfoExtra.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SC2APIProtocol.PlayerInfoExtra} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SC2APIProtocol.PlayerInfoExtra.toObject = function(includeInstance, msg) {
  var f, obj = {
    playerInfo: (f = msg.getPlayerInfo()) && proto.SC2APIProtocol.PlayerInfo.toObject(includeInstance, f),
    playerResult: (f = msg.getPlayerResult()) && proto.SC2APIProtocol.PlayerResult.toObject(includeInstance, f),
    playerMmr: jspb.Message.getField(msg, 3),
    playerApm: jspb.Message.getField(msg, 4)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SC2APIProtocol.PlayerInfoExtra}
 */
proto.SC2APIProtocol.PlayerInfoExtra.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SC2APIProtocol.PlayerInfoExtra;
  return proto.SC2APIProtocol.PlayerInfoExtra.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SC2APIProtocol.PlayerInfoExtra} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SC2APIProtocol.PlayerInfoExtra}
 */
proto.SC2APIProtocol.PlayerInfoExtra.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.SC2APIProtocol.PlayerInfo;
      reader.readMessage(value,proto.SC2APIProtocol.PlayerInfo.deserializeBinaryFromReader);
      msg.setPlayerInfo(value);
      break;
    case 2:
      var value = new proto.SC2APIProtocol.PlayerResult;
      reader.readMessage(value,proto.SC2APIProtocol.PlayerResult.deserializeBinaryFromReader);
      msg.setPlayerResult(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPlayerMmr(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPlayerApm(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SC2APIProtocol.PlayerInfoExtra.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SC2APIProtocol.PlayerInfoExtra} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SC2APIProtocol.PlayerInfoExtra.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayerInfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.SC2APIProtocol.PlayerInfo.serializeBinaryToWriter
    );
  }
  f = message.getPlayerResult();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.SC2APIProtocol.PlayerResult.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional PlayerInfo player_info = 1;
 * @return {?proto.SC2APIProtocol.PlayerInfo}
 */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.getPlayerInfo = function() {
  return /** @type{?proto.SC2APIProtocol.PlayerInfo} */ (
    jspb.Message.getWrapperField(this, proto.SC2APIProtocol.PlayerInfo, 1));
};


/** @param {?proto.SC2APIProtocol.PlayerInfo|undefined} value */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.setPlayerInfo = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.SC2APIProtocol.PlayerInfoExtra.prototype.clearPlayerInfo = function() {
  this.setPlayerInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.hasPlayerInfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional PlayerResult player_result = 2;
 * @return {?proto.SC2APIProtocol.PlayerResult}
 */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.getPlayerResult = function() {
  return /** @type{?proto.SC2APIProtocol.PlayerResult} */ (
    jspb.Message.getWrapperField(this, proto.SC2APIProtocol.PlayerResult, 2));
};


/** @param {?proto.SC2APIProtocol.PlayerResult|undefined} value */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.setPlayerResult = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.SC2APIProtocol.PlayerInfoExtra.prototype.clearPlayerResult = function() {
  this.setPlayerResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.hasPlayerResult = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 player_mmr = 3;
 * @return {number}
 */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.getPlayerMmr = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.setPlayerMmr = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.SC2APIProtocol.PlayerInfoExtra.prototype.clearPlayerMmr = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.hasPlayerMmr = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 player_apm = 4;
 * @return {number}
 */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.getPlayerApm = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.setPlayerApm = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.SC2APIProtocol.PlayerInfoExtra.prototype.clearPlayerApm = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SC2APIProtocol.PlayerInfoExtra.prototype.hasPlayerApm = function() {
  return jspb.Message.getField(this, 4) != null;
};


